# Generated by Django 5.0.1 on 2024-02-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ингридиенты')),
                ('count_measure', models.CharField(max_length=255, verbose_name='Мера измерения')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('buy_price', models.IntegerField(default=0, verbose_name='Цена покупки')),
                ('sell_price', models.IntegerField(default=0, verbose_name='Цена продажи')),
                ('date_in', models.TimeField(verbose_name='Дата поступления на склад')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
    ]
