# Generated by Django 5.0.1 on 2024-02-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingridients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridient',
            name='type',
            field=models.CharField(choices=[('meat', 'Мясо'), ('green', 'Зелень')], default='meat', max_length=255, verbose_name='Тип ингридиента'),
        ),
    ]
